server:
  port: 20000
#  servlet:
#    context-path: /coupon-template
eureka:
  client:
    service-url:
      # eureka的注册地址
      defaultZone: http://peer1:10000/eureka/,http://peer2:10001/eureka/

spring:
  application:
    name: coupon-template-service
  kafka:
    bootstrap-servers: 124.220.32.86:9092
    consumer:
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  rabbitmq:
    host: 124.220.32.86
    port: 5672
    username: guest
    password: guest

  datasource:
    # mysql数据源
    username: root
    password: 123456
    url: jdbc:mysql://124.220.32.86:3306/broadview_coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      connection-timeout: 20000
      idle-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 30000
      auto-commit: true
      pool-name: BroadviewCouponHikari
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect # sql 方言 mysql
    open-in-view: false
  cache:
    type: redis
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: 124.220.32.86:5672
      queue: zipkin

  redis:
    host: 124.220.32.86
    port: 6379
    # 连接超时时间
    timeout: 10000

logging:
  level:
    com.broadview.coupon: debug # 指定包debug

# actuator 开启所有management端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

broadview.rabbitmq.queue: broadview.queue
